# PyTorch

### PyTorch functions

PyTorch is an open source machine learning library which is commonly used for computer vision and natural language processing tasks. Is was developed 3 years ago by  Facebook's AI Research lab (FAIR). 
Pytorch is written in Python, C++, CUDA.
- Probability distributions - torch.distributions
- Init.uniform - produce uniform distrinutions
- Linspace/logspace - creates 1-D tensor with defined start and end elementes and fixed number of elements in a tensor
- Unbind - removes a tensor dimension along the given dimension
- Mean - for calculation mean value of tensor

In [80]:
# Import torch and numpy
import torch
import numpy as np

## Function 1 - distributions

Function distributions allows to generate different types of probability distribution. For example, Bernoulli distribution and Beta distribution.

In [81]:
# Example 1 - Bernoulli distribution
m = torch.distributions.Bernoulli(torch.tensor([0.6]))
m.sample() 

tensor([1.])

This function generates Bernoulli distribution with 60% chance 1 and 40% chance 0.

In [82]:
# Example 2 - Beta distribution
m = torch.distributions.Beta(torch.tensor([0.5]), torch.tensor([0.6]))
m.sample()

tensor([0.9965])

This function generates Beta distribution with concentration 0.5 and 0.6. 
1st concentration parameter of the distribution often referred to as alpha and 2nd concentration parameter of the distribution often referred to as beta. These concentration parameters can be float or Tensor.

In [83]:
# Example 3 - parameters of 
m = torch.distributions.Beta(torch.tensor([-1.]), torch.tensor([0.6]))
m.sample()

tensor([1.1755e-38])

Parameters of Beta distribution must be positive.

Parameters of probability distribution functions should be in accordance with mathematical definitions and physical meaning.

## Function 2 - init.uniform

This function allows to fill tensor by numbers from the uniform distribution with parameters a and b.

torch.nn.init.uniform_(tensor, a=0.0, b=1.0):

tensor – an n-dimensional torch.Tensor

a – the lower bound of the uniform distribution

b – the upper bound of the uniform distribution



In [84]:
# Example 1 - working
w = torch.empty(3, 5)
torch.nn.init.uniform_(w)

tensor([[0.9817, 0.9863, 0.9659, 0.7237, 0.8154],
        [0.7252, 0.0646, 0.9493, 0.3045, 0.1996],
        [0.9153, 0.8641, 0.0522, 0.8231, 0.0767]])

We create empty tensor and and initialize it with numbers from uniform distribution.

In [85]:
# Example 2 - uniform distribution from numpy array (converted to tensor)
arr = np.zeros(shape=(5,2))
tensor = torch.from_numpy(arr)
torch.nn.init.uniform_(tensor,a=-1.0, b=1.0)

tensor([[-0.1097,  0.1036],
        [ 0.4982, -0.2718],
        [ 0.7955, -0.2436],
        [ 0.6634, -0.9369],
        [-0.6476, -0.3754]], dtype=torch.float64)

We create np.array with zeros, transform numpy array to torch tensor and fils it with numbers from uniform distribution U(-1,1).

In [86]:
# Example 3 - input parameter in initialization function should be an n-dimensional torch.Tensor.
arr = np.zeros(shape=(5,2))
torch.nn.init.uniform_(arr,a=0.0, b=1.0)

AttributeError: 'numpy.ndarray' object has no attribute 'uniform_'

First input parameter in an torch.nn.init.uniform_(t,a,b) ahould be tensor.

This function can be used for weight initialization in an neural networks.

## Function 3 linspace

Returns a one-dimensional tensor of steps equally spaced points between start and end. The output tensor is 1-D of size steps.

In [87]:
# Example 1 - working
torch.linspace(-10, 10, steps=10)

tensor([-10.0000,  -7.7778,  -5.5556,  -3.3333,  -1.1111,   1.1111,   3.3333,
          5.5556,   7.7778,  10.0000])

The function returns 1-D tensor.

In [88]:
# Example 2 - working
torch.logspace(start=-1, end=1, steps=5, dtype=torch.float64)

tensor([ 0.1000,  0.3162,  1.0000,  3.1623, 10.0000], dtype=torch.float64)

Log scale in 1-D is created.

In [89]:
# Example 3 - breaking (to illustrate when it breaks)
torch.logspace(start=-10, end=10, steps=5, dtype=torch.complex64)

RuntimeError: Cannot register complex types without loading a library with complex support

Standart torch library doesn't support complex number in linspace and logspace functions.

The linspace and logspace functions can be used for creating 1-D tensors with real numbers.

## Function 4 - unbind

The function torch.unbind removes a tensor dimension along the given dimension dim
The default dimension is 0 i.e. dim=0

In [90]:
# Example 1
a = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
torch.unbind(a,dim=0)

(tensor([1, 2, 3]), tensor([4, 5, 6]))

One tensor is separated into two along horizontal axis.

In [91]:
# Example 2
a = torch.tensor([[1, 2, 3],
                  [4, 5, 6],
                 [7, 1, 9],
                 [4, 5, 10]])
torch.unbind(a,dim=1)

(tensor([1, 4, 7, 4]), tensor([2, 5, 1, 5]), tensor([ 3,  6,  9, 10]))

A tensor is separated into three along vertical axis.

In [92]:
# Example 3 - breaking (to illustrate when it breaks)
arr = np.zeros(shape=(5,2))
torch.unbind(arr)

TypeError: unbind(): argument 'input' (position 1) must be Tensor, not numpy.ndarray

Unbind function can be applied to tensor. If you want to apply it to numpy array it should be converted to torch.tensor.

This function can be used to remove a tensor dimension. 

## Function 5 - mean

Returns the mean value of all elements in the input tensor.

In [93]:
# Example 1 - working
random_tensor = torch.randn((2,5)) 
print(random_tensor)
torch.mean(random_tensor)

tensor([[-0.2361, -0.8353,  0.2157,  0.1530, -0.6881],
        [-0.2678, -1.4569, -0.0091,  0.7511, -0.2169]])


tensor(-0.2590)

We create a tensor of size 2x5 with randn function and calculated mean.

In [94]:
# Example 2 - working
random_tensor = torch.randn(4, 4)
print(random_tensor)
torch.mean(random_tensor, 1, True)

tensor([[-5.2877e-01, -6.1821e-01, -2.8932e+00, -5.8291e-01],
        [-7.5568e-01,  1.6655e+00, -2.7105e-01,  4.6165e-01],
        [ 9.2810e-01, -5.0297e-01,  1.3227e+00, -6.2785e-01],
        [ 6.5476e-01, -3.4316e-01, -9.6802e-04,  4.3275e-01]])


tensor([[-1.1558],
        [ 0.2751],
        [ 0.2800],
        [ 0.1858]])

Explanation about example

In [95]:
# Example 3 - breaking (to illustrate when it breaks)
bool_tensor = torch.tensor([0,0,1,1],dtype=torch.bool)
print(bool_tensor)
torch.mean(bool_tensor)

tensor([False, False,  True,  True], dtype=torch.bool)


RuntimeError: Can only calculate the mean of floating types. Got Bool instead.

The mean function only for tensors of floating types.

Can be used for floating types tensors for calculationg mean values for defenite axis.

## Conclusion

We discuss Probability distributions, Init.uniform, Linspace/logspace, unbind and mean functions. All of them can be applyed for a tensors, but some of them have restrictions. Linspace/logspace can not be used to generate 1-D complex tensor. A unbind applyed only for tensors - if we want to use this function to array we need to convert numpy array to tensor previously. A mean function applied only for numeric tensors.

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html
* https://towardsdatascience.com/useful-pytorch-functions-356de5f31a1e

In [96]:
!pip install jovian --upgrade --quiet

In [97]:
import jovian

<IPython.core.display.Javascript object>

In [98]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Please enter your API key ( from https://jovian.ml/ ):
API KEY: ········
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/medvedeva-svetlana-yu/01-tensor-operations-252a8


'https://jovian.ml/medvedeva-svetlana-yu/01-tensor-operations-252a8'